version: '3.8'
name: 'group_project_backend'

networks:
  database_server:
    external: true

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - 8080:${PORT}
    restart: always
    networks:
      - database_server