version: '3.8'
name: 'e-wallet'

networks:
  server:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    env_file:
      - .env