package seeder

import (
	"git.garena.com/sea-labs-id/bootcamp/batch-01/group-project/pejuang-rupiah/backend/constant"
	"git.garena.com/sea-labs-id/bootcamp/batch-01/group-project/pejuang-rupiah/backend/model"
	"github.com/shopspring/decimal"
)

var ProductOrders = []model.ProductOrders{
	{
		ID:            1,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(15000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderOnProcess,
	},
	{
		ID:            2,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderDelivered,
	},
	{
		ID:            3,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(17000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusCanceled,
	},
	{
		ID:            4,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderCompleted,
	},
	{
		ID:            5,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderCompleted,
	},
	{
		ID:            6,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderCompleted,
	},
	{
		ID:            7,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderCompleted,
	},
	{
		ID:            8,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderCompleted,
	},
	{
		ID:            9,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderCompleted,
	},
	{
		ID:            10,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderCompleted,
	},
	{
		ID:            11,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderCompleted,
	},
	{
		ID:            12,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderCompleted,
	},
	{
		ID:            13,
		CourierName:   "jne",
		AccountID:     2,
		DeliveryFee:   decimal.NewFromInt(20000),
		Province:      "Jawa Barat",
		District:      "Kabupaten Bandung",
		SubDistrict:   "Bojongsoang",
		Kelurahan:     "Sukapura",
		ZipCode:       "40851",
		AddressDetail: "Jl Telekomunikasi No 1 Bojongsoang",
		Status:        constant.StatusOrderCompleted,
	},
}
