package seeder

import (
	"git.garena.com/sea-labs-id/bootcamp/batch-01/group-project/pejuang-rupiah/backend/model"
	"github.com/shopspring/decimal"
)

var ProductVariantSelectionCombinations = []*model.ProductVariantSelectionCombinations{
	{
		ID:                         7,
		ProductID:                  4,
		ProductVariantSelectionID1: 8,
		Price:                      decimal.NewFromInt(15000),
		Stock:                      12,
	},
	{
		ID:                         8,
		ProductID:                  5,
		ProductVariantSelectionID1: 9,
		ProductVariantSelectionID2: 18,
		Price:                      decimal.NewFromInt(17000),
		Stock:                      12,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukw-lfp3yqtb7kgy70",
	},
	{
		ID:                         9,
		ProductID:                  5,
		ProductVariantSelectionID1: 9,
		ProductVariantSelectionID2: 19,
		Price:                      decimal.NewFromInt(20000),
		Stock:                      29,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukw-lfp3yqtb7kgy70",
	},
	{
		ID:                         10,
		ProductID:                  5,
		ProductVariantSelectionID1: 9,
		ProductVariantSelectionID2: 20,
		Price:                      decimal.NewFromInt(19000),
		Stock:                      32,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukw-lfp3yqtb7kgy70",
	},
	{
		ID:                         11,
		ProductID:                  5,
		ProductVariantSelectionID1: 9,
		ProductVariantSelectionID2: 21,
		Price:                      decimal.NewFromInt(18000),
		Stock:                      89,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukw-lfp3yqtb7kgy70",
	},
	{
		ID:                         12,
		ProductID:                  5,
		ProductVariantSelectionID1: 9,
		ProductVariantSelectionID2: 22,
		Price:                      decimal.NewFromInt(17500),
		Stock:                      102,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukw-lfp3yqtb7kgy70",
	},
	{
		ID:                         13,
		ProductID:                  5,
		ProductVariantSelectionID1: 10,
		ProductVariantSelectionID2: 18,
		Price:                      decimal.NewFromInt(16500),
		Stock:                      89,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul3-lfp3yqtb8z1ea0",
	},
	{
		ID:                         14,
		ProductID:                  5,
		ProductVariantSelectionID1: 10,
		ProductVariantSelectionID2: 19,
		Price:                      decimal.NewFromInt(15000),
		Stock:                      78,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul3-lfp3yqtb8z1ea0",
	},
	{
		ID:                         15,
		ProductID:                  5,
		ProductVariantSelectionID1: 10,
		ProductVariantSelectionID2: 20,
		Price:                      decimal.NewFromInt(15500),
		Stock:                      73,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul3-lfp3yqtb8z1ea0",
	},
	{
		ID:                         16,
		ProductID:                  5,
		ProductVariantSelectionID1: 10,
		ProductVariantSelectionID2: 21,
		Price:                      decimal.NewFromInt(24000),
		Stock:                      23,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul3-lfp3yqtb8z1ea0",
	},
	{
		ID:                         17,
		ProductID:                  5,
		ProductVariantSelectionID1: 10,
		ProductVariantSelectionID2: 22,
		Price:                      decimal.NewFromInt(19500),
		Stock:                      62,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul3-lfp3yqtb8z1ea0",
	},
	{
		ID:                         18,
		ProductID:                  5,
		ProductVariantSelectionID1: 11,
		ProductVariantSelectionID2: 18,
		Price:                      decimal.NewFromInt(18500),
		Stock:                      69,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul5-lfp3yqtbadlu72",
	},
	{
		ID:                         19,
		ProductID:                  5,
		ProductVariantSelectionID1: 11,
		ProductVariantSelectionID2: 19,
		Price:                      decimal.NewFromInt(19000),
		Stock:                      63,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul5-lfp3yqtbadlu72",
	},
	{
		ID:                         20,
		ProductID:                  5,
		ProductVariantSelectionID1: 11,
		ProductVariantSelectionID2: 20,
		Price:                      decimal.NewFromInt(21000),
		Stock:                      37,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul5-lfp3yqtbadlu72",
	},
	{
		ID:                         21,
		ProductID:                  5,
		ProductVariantSelectionID1: 11,
		ProductVariantSelectionID2: 21,
		Price:                      decimal.NewFromInt(23500),
		Stock:                      63,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul5-lfp3yqtbadlu72",
	},
	{
		ID:                         22,
		ProductID:                  5,
		ProductVariantSelectionID1: 11,
		ProductVariantSelectionID2: 22,
		Price:                      decimal.NewFromInt(24500),
		Stock:                      57,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul5-lfp3yqtbadlu72",
	},
	{
		ID:                         23,
		ProductID:                  5,
		ProductVariantSelectionID1: 12,
		ProductVariantSelectionID2: 18,
		Price:                      decimal.NewFromInt(21500),
		Stock:                      95,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukx-lfp3yqtbbs6aee",
	},
	{
		ID:                         24,
		ProductID:                  5,
		ProductVariantSelectionID1: 12,
		ProductVariantSelectionID2: 19,
		Price:                      decimal.NewFromInt(23000),
		Stock:                      27,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukx-lfp3yqtbbs6aee",
	},
	{
		ID:                         25,
		ProductID:                  5,
		ProductVariantSelectionID1: 12,
		ProductVariantSelectionID2: 20,
		Price:                      decimal.NewFromInt(21000),
		Stock:                      96,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukx-lfp3yqtbbs6aee",
	},
	{
		ID:                         26,
		ProductID:                  5,
		ProductVariantSelectionID1: 12,
		ProductVariantSelectionID2: 21,
		Price:                      decimal.NewFromInt(24500),
		Stock:                      55,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukx-lfp3yqtbbs6aee",
	},
	{
		ID:                         27,
		ProductID:                  5,
		ProductVariantSelectionID1: 12,
		ProductVariantSelectionID2: 22,
		Price:                      decimal.NewFromInt(23000),
		Stock:                      29,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukx-lfp3yqtbbs6aee",
	},
	{
		ID:                         28,
		ProductID:                  5,
		ProductVariantSelectionID1: 13,
		ProductVariantSelectionID2: 18,
		Price:                      decimal.NewFromInt(19000),
		Stock:                      0,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7quky-ligq1ncox2eifa",
	},
	{
		ID:                         29,
		ProductID:                  5,
		ProductVariantSelectionID1: 13,
		ProductVariantSelectionID2: 19,
		Price:                      decimal.NewFromInt(21000),
		Stock:                      26,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7quky-ligq1ncox2eifa",
	},
	{
		ID:                         30,
		ProductID:                  5,
		ProductVariantSelectionID1: 13,
		ProductVariantSelectionID2: 20,
		Price:                      decimal.NewFromInt(22000),
		Stock:                      0,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7quky-ligq1ncox2eifa",
	},
	{
		ID:                         31,
		ProductID:                  5,
		ProductVariantSelectionID1: 13,
		ProductVariantSelectionID2: 21,
		Price:                      decimal.NewFromInt(23500),
		Stock:                      18,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7quky-ligq1ncox2eifa",
	},
	{
		ID:                         32,
		ProductID:                  5,
		ProductVariantSelectionID1: 13,
		ProductVariantSelectionID2: 22,
		Price:                      decimal.NewFromInt(24500),
		Stock:                      95,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7quky-ligq1ncox2eifa",
	},
	{
		ID:                         33,
		ProductID:                  5,
		ProductVariantSelectionID1: 14,
		ProductVariantSelectionID2: 18,
		Price:                      decimal.NewFromInt(18000),
		Stock:                      37,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul2-ligq1ncovnu24b",
	},
	{
		ID:                         34,
		ProductID:                  5,
		ProductVariantSelectionID1: 14,
		ProductVariantSelectionID2: 19,
		Price:                      decimal.NewFromInt(18000),
		Stock:                      0,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul2-ligq1ncovnu24b",
	},
	{
		ID:                         35,
		ProductID:                  5,
		ProductVariantSelectionID1: 14,
		ProductVariantSelectionID2: 20,
		Price:                      decimal.NewFromInt(19000),
		Stock:                      73,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul2-ligq1ncovnu24b",
	},
	{
		ID:                         36,
		ProductID:                  5,
		ProductVariantSelectionID1: 14,
		ProductVariantSelectionID2: 21,
		Price:                      decimal.NewFromInt(23000),
		Stock:                      95,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul2-ligq1ncovnu24b",
	},
	{
		ID:                         37,
		ProductID:                  5,
		ProductVariantSelectionID1: 14,
		ProductVariantSelectionID2: 22,
		Price:                      decimal.NewFromInt(20000),
		Stock:                      25,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul2-ligq1ncovnu24b",
	},
	{
		ID:                         38,
		ProductID:                  5,
		ProductVariantSelectionID1: 15,
		ProductVariantSelectionID2: 18,
		Price:                      decimal.NewFromInt(23000),
		Stock:                      0,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul1-ligq1ncp1a3ue0",
	},
	{
		ID:                         39,
		ProductID:                  5,
		ProductVariantSelectionID1: 15,
		ProductVariantSelectionID2: 19,
		Price:                      decimal.NewFromInt(21000),
		Stock:                      64,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul1-ligq1ncp1a3ue0",
	},
	{
		ID:                         40,
		ProductID:                  5,
		ProductVariantSelectionID1: 15,
		ProductVariantSelectionID2: 20,
		Price:                      decimal.NewFromInt(18900),
		Stock:                      89,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul1-ligq1ncp1a3ue0",
	},
	{
		ID:                         41,
		ProductID:                  5,
		ProductVariantSelectionID1: 15,
		ProductVariantSelectionID2: 21,
		Price:                      decimal.NewFromInt(17000),
		Stock:                      53,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul1-ligq1ncp1a3ue0",
	},
	{
		ID:                         42,
		ProductID:                  5,
		ProductVariantSelectionID1: 15,
		ProductVariantSelectionID2: 22,
		Price:                      decimal.NewFromInt(18500),
		Stock:                      78,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul1-ligq1ncp1a3ue0",
	},
	{
		ID:                         43,
		ProductID:                  5,
		ProductVariantSelectionID1: 16,
		ProductVariantSelectionID2: 18,
		Price:                      decimal.NewFromInt(19000),
		Stock:                      0,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul1-ligq1ncozvjea6",
	},
	{
		ID:                         44,
		ProductID:                  5,
		ProductVariantSelectionID1: 16,
		ProductVariantSelectionID2: 19,
		Price:                      decimal.NewFromInt(15500),
		Stock:                      74,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul1-ligq1ncozvjea6",
	},
	{
		ID:                         45,
		ProductID:                  5,
		ProductVariantSelectionID1: 16,
		ProductVariantSelectionID2: 20,
		Price:                      decimal.NewFromInt(16500),
		Stock:                      25,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul1-ligq1ncozvjea6",
	},
	{
		ID:                         46,
		ProductID:                  5,
		ProductVariantSelectionID1: 16,
		ProductVariantSelectionID2: 21,
		Price:                      decimal.NewFromInt(17500),
		Stock:                      53,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul1-ligq1ncozvjea6",
	},
	{
		ID:                         47,
		ProductID:                  5,
		ProductVariantSelectionID1: 16,
		ProductVariantSelectionID2: 22,
		Price:                      decimal.NewFromInt(21000),
		Stock:                      79,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qul1-ligq1ncozvjea6",
	},
	{
		ID:                         48,
		ProductID:                  5,
		ProductVariantSelectionID1: 17,
		ProductVariantSelectionID2: 18,
		Price:                      decimal.NewFromInt(18000),
		Stock:                      64,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukz-ligq1ncoygyybc",
	},
	{
		ID:                         49,
		ProductID:                  5,
		ProductVariantSelectionID1: 17,
		ProductVariantSelectionID2: 19,
		Price:                      decimal.NewFromInt(14000),
		Stock:                      39,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukz-ligq1ncoygyybc",
	},
	{
		ID:                         50,
		ProductID:                  5,
		ProductVariantSelectionID1: 17,
		ProductVariantSelectionID2: 20,
		Price:                      decimal.NewFromInt(16000),
		Stock:                      76,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukz-ligq1ncoygyybc",
	},
	{
		ID:                         51,
		ProductID:                  5,
		ProductVariantSelectionID1: 17,
		ProductVariantSelectionID2: 21,
		Price:                      decimal.NewFromInt(15000),
		Stock:                      80,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukz-ligq1ncoygyybc",
	},
	{
		ID:                         52,
		ProductID:                  5,
		ProductVariantSelectionID1: 17,
		ProductVariantSelectionID2: 22,
		Price:                      decimal.NewFromInt(15100),
		Stock:                      0,
		PictureURL:                 "https://down-id.img.susercontent.com/file/id-11134207-7qukz-ligq1ncoygyybc",
	},
	{
		ID:                         53,
		ProductID:                  6,
		ProductVariantSelectionID1: 23,
		Price:                      decimal.NewFromInt(40000),
		Stock:                      16,
		PictureURL:                 "https://down-id.img.susercontent.com/file/ca5c8d2e02695789369e2ed4a403f9ae",
	},
	{
		ID:                         54,
		ProductID:                  6,
		ProductVariantSelectionID1: 24,
		Price:                      decimal.NewFromInt(40000),
		Stock:                      43,
		PictureURL:                 "https://down-id.img.susercontent.com/file/074bf8077206bfa5cc06e4594a433e46",
	},
	{
		ID:                         55,
		ProductID:                  6,
		ProductVariantSelectionID1: 25,
		Price:                      decimal.NewFromInt(36000),
		Stock:                      167,
		PictureURL:                 "https://down-id.img.susercontent.com/file/403e8775239379f5553e70eb19cf1619",
	},
	{
		ID:                         56,
		ProductID:                  6,
		ProductVariantSelectionID1: 26,
		Price:                      decimal.NewFromInt(48000),
		Stock:                      97,
		PictureURL:                 "https://down-id.img.susercontent.com/file/65986fc67c09afc94b5eb8ae60b5ccb6",
	},
	{
		ID:                         57,
		ProductID:                  6,
		ProductVariantSelectionID1: 27,
		Price:                      decimal.NewFromInt(44000),
		Stock:                      168,
		PictureURL:                 "https://down-id.img.susercontent.com/file/sg-11134201-22100-hp9lhpqoz4hvb1",
	},
	{
		ID:                         58,
		ProductID:                  6,
		ProductVariantSelectionID1: 28,
		Price:                      decimal.NewFromInt(49000),
		Stock:                      156,
		PictureURL:                 "https://down-id.img.susercontent.com/file/30451051fed2877b09beebb025a52dca",
	},
	{
		ID:                         59,
		ProductID:                  6,
		ProductVariantSelectionID1: 29,
		Price:                      decimal.NewFromInt(37000),
		Stock:                      172,
		PictureURL:                 "https://down-id.img.susercontent.com/file/15caffb5ad6ca9d3e2c5188cf580f0e6",
	},
	{
		ID:                         60,
		ProductID:                  6,
		ProductVariantSelectionID1: 30,
		Price:                      decimal.NewFromInt(42000),
		Stock:                      165,
		PictureURL:                 "https://down-id.img.susercontent.com/file/f0f5bfbbbf8faefc0e7de39493933d84",
	},
	{
		ID:                         61,
		ProductID:                  6,
		ProductVariantSelectionID1: 31,
		Price:                      decimal.NewFromInt(46000),
		Stock:                      190,
		PictureURL:                 "https://down-id.img.susercontent.com/file/5bc0cfde42f1ef34dc730e34b5322d5e",
	},
	{
		ID:                         62,
		ProductID:                  6,
		ProductVariantSelectionID1: 32,
		Price:                      decimal.NewFromInt(44000),
		Stock:                      93,
		PictureURL:                 "https://down-id.img.susercontent.com/file/4d549ac7f2fc2c66b2ff67b534de6c47",
	},
	{
		ID:                         63,
		ProductID:                  6,
		ProductVariantSelectionID1: 33,
		Price:                      decimal.NewFromInt(43000),
		Stock:                      167,
		PictureURL:                 "https://down-id.img.susercontent.com/file/sg-11134201-22100-uifcpyhrt7hvea",
	},
	{
		ID:                         64,
		ProductID:                  6,
		ProductVariantSelectionID1: 34,
		Price:                      decimal.NewFromInt(45000),
		Stock:                      180,
		PictureURL:                 "https://down-id.img.susercontent.com/file/sg-11134201-22100-p41flzmjt7hvcc",
	},
	{
		ID:                         65,
		ProductID:                  6,
		ProductVariantSelectionID1: 35,
		Price:                      decimal.NewFromInt(37000),
		Stock:                      94,
		PictureURL:                 "https://down-id.img.susercontent.com/file/sg-11134201-22110-8qkazkh8gqjv7a",
	},
	{
		ID:                         66,
		ProductID:                  6,
		ProductVariantSelectionID1: 36,
		Price:                      decimal.NewFromInt(41000),
		Stock:                      119,
		PictureURL:                 "https://down-id.img.susercontent.com/file/sg-11134201-22110-aetzrwn8gqjv56",
	},
	{
		ID:                         67,
		ProductID:                  6,
		ProductVariantSelectionID1: 37,
		Price:                      decimal.NewFromInt(39000),
		Stock:                      115,
		PictureURL:                 "https://down-id.img.susercontent.com/file/sg-11134201-22110-g7mpxaw8gqjv74",
	},
	{
		ID:                         68,
		ProductID:                  6,
		ProductVariantSelectionID1: 38,
		Price:                      decimal.NewFromInt(42000),
		Stock:                      154,
		PictureURL:                 "https://down-id.img.susercontent.com/file/sg-11134201-22110-v6fjqy48gqjvc1",
	},
	{
		ID:                         69,
		ProductID:                  6,
		ProductVariantSelectionID1: 39,
		Price:                      decimal.NewFromInt(35000),
		Stock:                      77,
		PictureURL:                 "https://down-id.img.susercontent.com/file/sg-11134201-22110-mz2h5uz8gqjvad",
	},
	{
		ID:                         70,
		ProductID:                  6,
		ProductVariantSelectionID1: 40,
		Price:                      decimal.NewFromInt(40000),
		Stock:                      80,
		PictureURL:                 "https://down-id.img.susercontent.com/file/sg-11134201-22110-q7tn7ed9gqjv86",
	},
	{
		ID:                         71,
		ProductID:                  7,
		ProductVariantSelectionID1: 41,
		Price:                      decimal.NewFromInt(150000),
		Stock:                      80,
	},
	{
		ID:                         72,
		ProductID:                  8,
		ProductVariantSelectionID1: 42,
		Price:                      decimal.NewFromInt(359000),
		Stock:                      890,
	},
	{
		ID:                         73,
		ProductID:                  9,
		ProductVariantSelectionID1: 43,
		Price:                      decimal.NewFromInt(148100),
		Stock:                      360,
	},
	{
		ID:                         74,
		ProductID:                  10,
		ProductVariantSelectionID1: 44,
		Price:                      decimal.NewFromInt(1151040),
		Stock:                      16,
	},
	{
		ID:                         75,
		ProductID:                  11,
		ProductVariantSelectionID1: 45,
		Price:                      decimal.NewFromInt(112000),
		Stock:                      78,
	},
	{
		ID:                         76,
		ProductID:                  12,
		ProductVariantSelectionID1: 46,
		Price:                      decimal.NewFromInt(36600),
		Stock:                      38,
	},
	{
		ID:                         77,
		ProductID:                  13,
		ProductVariantSelectionID1: 47,
		Price:                      decimal.NewFromInt(200000),
		Stock:                      328,
	},
	{
		ID:                         78,
		ProductID:                  14,
		ProductVariantSelectionID1: 48,
		Price:                      decimal.NewFromInt(150000),
		Stock:                      232,
	},
	{
		ID:                         79,
		ProductID:                  15,
		ProductVariantSelectionID1: 49,
		Price:                      decimal.NewFromInt(40000),
		Stock:                      875,
	},
	{
		ID:                         80,
		ProductID:                  16,
		ProductVariantSelectionID1: 50,
		Price:                      decimal.NewFromInt(100000),
		Stock:                      439,
	},
	{
		ID:                         81,
		ProductID:                  17,
		ProductVariantSelectionID1: 51,
		Price:                      decimal.NewFromInt(22000),
		Stock:                      123,
	},
	{
		ID:                         82,
		ProductID:                  18,
		ProductVariantSelectionID1: 52,
		Price:                      decimal.NewFromInt(75000),
		Stock:                      37,
	},
	{
		ID:                         83,
		ProductID:                  19,
		ProductVariantSelectionID1: 53,
		Price:                      decimal.NewFromInt(60000),
		Stock:                      213,
	},
	{
		ID:                         84,
		ProductID:                  20,
		ProductVariantSelectionID1: 54,
		Price:                      decimal.NewFromInt(150000),
		Stock:                      21,
	},
	{
		ID:                         85,
		ProductID:                  21,
		ProductVariantSelectionID1: 55,
		Price:                      decimal.NewFromInt(65000),
		Stock:                      22,
	},
	{
		ID:                         86,
		ProductID:                  22,
		ProductVariantSelectionID1: 56,
		Price:                      decimal.NewFromInt(52000),
		Stock:                      98,
	},
	{
		ID:                         87,
		ProductID:                  23,
		ProductVariantSelectionID1: 57,
		Price:                      decimal.NewFromInt(60000),
		Stock:                      28,
	},
}
