package seeder

import (
	"time"

	"git.garena.com/sea-labs-id/bootcamp/batch-01/group-project/pejuang-rupiah/backend/model"
	"github.com/shopspring/decimal"
)

var Products = []*model.Products{
	{
		ID:                4,
		Name:              `Kalung 100% Titanium Rollo + Cincin Pria Dan wanita [ Toko Metal ]`,
		Description:       `Kalung Titanium Rollo + Liontin Cincin\n\n *Keterangan Produk.\n- Rantai Kalung Rolo\n -Panjang Kalung : 60 cm\n- Dm Kalung : 2 mm\n- Warna : - Silver \n-Material Kalung : 100%Titanium Stainless Steel Asli. \n\nCincin Bahan Titanium\n\n***Untuk Ukuran cincin bisa reaquest size lewat chat atau cantumkan dicatatan\n***Jika tidak mecantumkan size cincin kami kirim ukuran random🙏🏼\n\nWarna tidak akan berubah,Tidak berkarat,tidak korosi dan tidak mengelupas / tidak luntur -Struktur sangat halus,rapi dan sangat nyaman dipakai. Tidak menyebabkan alergi /gatal gatal pada kulit sensitive. Aman juga dipakai oleh anak anak Kalung pria wanita /TITANIUM 316L STAINLESS STEEL`,
		CategoryID:        767,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(10),
		Size:              decimal.NewFromInt(20),
		IsNew:             true,
		InternalSKU:       "asd82adwa",
		ViewCount:         38,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                5,
		Name:              `KOMIN-Sandal Hiu Pria Dewasa Sendal Shark Sandal Couple Rumah Sendal Paus Eva Lembut Ringan Nyaman Sandal Pasangan Korea`,
		Description:       `👇Informasi Produk:\n🎈Merek:Komin\n🎈Warna:Black/Pink//Yellow/Grey\n🎈Ukuran:34-45\nUkuran 36/37 = 22.50 cm-23.50 cm\nUkuran 38/39 = 24.00 cm-24.50 cm\nUkuran 40/41 = 25.00 cm-25.50 cm\nUkuran 42/43 = 27.00 cm-27.50cm\nUkuran 44/45 = 29.00 cm-29.50cm`,
		CategoryID:        772,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "asd82gkwa",
		ViewCount:         38,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                6,
		Name:              `Bitzen Ikat Pinggang Pria Nylon Canvas Sabuk Berkualitas Premium`,
		Description:       `Ikat pinggang nylon canvas  \n\nmembuat penampilan anda menarik dan keren, dengan desain fast unlock tidak repot pada saat memakainya.\n\n\n\nVarian Warna yang :\n\n- HITAM\n\n- ABU\n\n- HIJAU\n\n- BIRU\n\n-HITAM&Cream(double sided)\n\n-HITAM&Khaki(double sided)\n\n-ABU&HIJAU(double sided)\n\n-ABU&BIRU(double sided)\n\n\n\n\n\nMerek:Bitzen \n\n\n\nbuckle : Zinc Alloy Bahan belt \n\nsabuk : Nylon Canvas\n\n\n\nDimensi :\n\nlebar tali : 3.8cm\n\npanjang tali: 120cm`,
		CategoryID:        697,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "as52adwa",
		ViewCount:         28,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                7,
		Name:              `Gizmo Celana Cargo Jeans Pria Loose fit reguler gombrong / Cargo pants Jeans Reguler Standard Denim washed Bluewash`,
		Description:       `Cargo jeans saat ini merupakan salah satu pilihan terbaik dan merupakan must-have bagi para pria.\n\nGizmo Cargo Jeans ini di design Fashionable untuk dipakai berbagai aktifitas baik indoor ataupun outdoor\n\nMenggunakan bahan jeans berkualitas tinggi sehingga nyaman dipakai, dinggin, tidak luntur, tidak berbulu dan kuat dipakai bertahun-tahun.\n\nNyaman dipakai dan pastinya Worthit Banget!\n\nModel modis dan stylist recomended banget buat santai namun tetap modis.\n\nCocok buat jalan² / OOTD / Traveling / Kegiatan outdoor\n\nMemiliki live-button, Resleting, Belt loop, dan tedapat 6 saku yang pasti membantu banget bagi kalian yang sering membawa banyak barang sekaligus.\n\nDengan tersedianya beragam warna, kamu bakalan mudah banget memadukan celana ini dengan berbagai outfit yang kamu punya.\n\nDengan cuttingan Loose pants ini kamu cukup mix n match dengan kaos oversize ataupun sweater polos saja auto penampilan kamu bakalan hypebeast, tambah keren dan bisa langsung OOTD\n\nTalent :\nTinggi Model 170cm\nBerat Model 60kg\nModel menggunakan size 30\n\nDetails:\nCotton Twill Premium\nMidweight\nRegular Cut\n2 Pocket Below the Waist\n2 Cargo Pocket on Side\n2 Pocket on Back\nWoven Label\nZipper Premium\n\nSize Chart:\n28= Lingkar Pinggang 80cm x Lingkar Paha 56cm x Panjang 102cm x Open Leg 42cm\n30= Lingkar Pinggang 84cm x Lingkar Paha 58cm x Panjang 102cm x Open Leg 44cm\n32= Lingkar Pinggang 88cm x Lingkar Paha 62cm x Panjang 104cm x Open Leg 46cm\n34= Lingkar Pinggang 93cm x Lingkar Paha 64cm x Panjang 104cm x Open Leg 48cm\n36= Lingkar Pinggang 99cm x Lingkar Paha 66cm x Panjang 105cm x Open Leg 50cm\n38= Lingkar Pinggang 104cm x Lingkar Paha 70cm x Panjang 105cm x Open Leg 52cm\n\n\nEstimasi size 2cm sebagaimana produksi masal\n\nLangsung order guys dijamin Worth it Bangett..`,
		CategoryID:        738,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "aawdkadwa",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                8,
		Name:              `( REFLECTIVE ) Sepatu Sneakers AlR MX 97 Undefeted White Black Silver Bullet`,
		Description:       `Baca Selengkapnya\n\nDetail Produk\n\n" INFORMASI PRODUK "\n----------------------------------------------------------------------\nType : Sneakers\nMade in Vietnam\nAvailable Size :36-44\nSize Guide women : 36= 22,5cm | 37 = 23 cm | 38 = 23,5cm | 39 = 24,5cm | 40= 25cm | 41 = 26cm | 42 = 27cm | 43 = 28cm | 44 = 29cm\n\n" CATATAN PENTING MOHON DI PERHATIKAN "\n-----------------------------------------------------------------------\nBarang yang di foto 100% mirip dengan aslinya (hasil foto langsung)\nBarang yang kami kirim 100% baru Include box sesuai merk Sepatu + Kaos Kaki..\nBila barang reject atau size tdk sesuai brang bisa di tukar dengan kondisi barang BELUM di pakai..\n\nApabila ada yang ingin di Tanyakan / kurang mengerti , jangan sungkan bertanya kpd Kami. Kami siap secepatnya untuk Merespon\n\nDemi kenyamanan dalam melakukan transaksi , alangkah baiknya melakukan tanya jawab terlebih dahulu untuk mengetahui ketersediaan Stok Baik Ukuran ataupun Warna. \n\n`,
		CategoryID:        2153,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "as4tg3kedwa",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:   9,
		Name: `Sendal Crocs Classic clogs / Clog / Sandal Perawat / Suster / Mantri / Karet / Classics / Slip on karet pria wanita / Sandal tahan air`,
		Description: `Classic Crocs Original\n\nPenenun keset sarang lebah.\nKETERANGAN INSOLE :\n\nM4 : 36-37 = 23cm\nM5 : 37-38 = 24cm\nM6 : 39 = 24.5cm\nM7 : 40 = 25cm\nM8 : 41 = 26cm\nM9 : 42 = 27cm\nM10 : 43-44 = 28cm-28.5cm\nM11 : 44-45 = 29cm-29.5cm\n\nSendal paling BEST SELLER dan nyaman dipakai, dibersihinnya juga gampang, mau basahan juga enak.. TIDAK LICIN \n\nSUPER EMPUK, garansi uang kembali, kalau NGGA EMPUK !! \n•	Kondisi : 100% Baru\n•	Bahan : Full Rubber-Anti Licin) \n\nkualitas barang dan ketepatan dalam pengiriman barang menjadi MODAL KEPERCAYAAN KONSUMEN terhadap kami...`,
		CategoryID:        772,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "4gtmkedwa",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                10,
		Name:              `Jam Tangan Pria Parlent Gallant Prime`,
		Description:       `Mesin Automatic - Seagull St1646\n40 Jam Power Reserve\n5 Atm (50 Meter)\nUpgrade Dari Gallant Vortex\nDiameter 42 mm\nQuick Release Strap\nMemiliki Skeleton Dial\nTersedia Warna Gold, Black, Silver\n`,
		CategoryID:        735,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "4gtmjkfdwa",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                11,
		Name:              `Sweater Hoodie Jaket Polos size Jumbo XXL Oversize | Hoodie Jaket Korean Style Oversize | Hoodie Sweater Jaket Premium Distro`,
		Description:       `Material : fleece cotton\n~Size : all size fit to XXL - 3XL-  XL ( LD 132 CM PJ 72 CM \n\n~free ongkir \n~ GOOD QUALLITY FREMIUM 👍 di jamin tebal \n\nReal pict ( BEST SELLER ) \n\nSweater yang cocok untuk sista yang selalu mengikuti trend kekinian dan juga fashionable\nkarna bahan lembut juga tidak mudah kusut tentunya menambah kesan rapih 😍 \n\nhissss jangan ragu ya sista karna Kemiripan barang 98% karna kita buat semirip mungkin dengan gambar .jadi apa yang kaka liat itu yang akan kaka dapatkan. \nburuan di order sebelum stok kehabisan \n\nJam Oprasional : \nSenin s/d sabtu : 09.00-14: 30\n*INPUT NO RESI H+1 SETELAH BARANG  D KIRIM\n*HARI MINGGU TIDAK ADA PENGIRIMAN, JADI BARANG D KIRIM KEESOKAN HARINYA. \n\nHAPPY SHOPING \n\n#sweaterwanita #sweaterrounhand #sweatercrop #jaketvarsity #hoodiepolos #hoodietiedye #sweaterpria #hoodiepria #outwear #sweaterkorea #sweatermurah #sweterpolos #sweateroblong #jaketbaseball # jaketbomber #jaketcrop`,
		CategoryID:        882,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "4g342kkfdwa",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                12,
		Name:              `Vallina - Lunaya Outer Crop Plained Premium Outerwear Sweater Crope Polos Remaja Wanita Korean Style`,
		Description:       `Vallina Outfit saat ini merupakan salah satu lini outfit muslim terbaik dan berkualitas tinggi di antara Local Brand Indonesia. \n\nBahan: Fleece \nUkuran: One Size Fit L \nLD: 102 cm (-+)\nKualitas Premium\n\n**Warna yang terlihat pada gambar mungkin tidak 100% sama dengan produk yang sebenarnya, disebabkan faktor lighting pada proses photoshoot, atau kondisi gadget yang digunakan untuk melihat gambar\n\n**Pastikan alamat yang di tulis ketika checkout diisi dengan sangan LENGKAP guna menghindari kendala pengiriman oleh kurir (Sertakan patokan bila perlu)\n**Pastikan nomor HP yang diisi dalam alamat ketika checkout mudah dihubungi (Tlp. & Sms) / (Sertakan 2 Nomor Hp bila perlu)`,
		CategoryID:        882,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "4g4kwtnkwdwa",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                13,
		Name:              `AUFCO Celana Cargo Panjang AUFCO Warna Greenarmy bahan Kualitas Premium Grade A`,
		Description:       `Auf.co Cargo Pants adalah yang terbaik di kelasnya. Siapa yang tak kenal Cargo Pants? Sebuah fashion-items yang sepertinya sudah layak disebut wajib untuk dimiliki oleh setiap lelaki. Sooo...Its time to support your local !\nAuf.co Cargo Pants diproduksi dengan bahan terbaik sehingga tak menimbulkan rasa gerah dan tak mudah memulur.\nTak percaya? Coba saja ! ;)\n\n\n\nModel : Standar Fit\n\nTersedia 7 Warna : \n- Black\n- Cream\n- Green Army\n- Blue NAvy\n- Light Grey\n- Dark Grey\n- Mocca\n\nReady Size : S M L XL 2XL 3XL 4XL 5XL\n\n√Realpict 100%\n√Premium Material 100%\n√100% Original\n\nSize tersedia \n-S fit 27-28 : pinggang 76 panjang 92\n-M fit 29-30 : pinggang 80 panjang 93\n-L fit 31-32 : pinggang 84 panjang 94\n-XL fit 33-34 : pinggang 88 panjang 95\n-2XL fit 35-36 pinggang 92 panjang 96\n-3XL fit 37-38 pinggang 96 panjang 97\n-4XL fit 39-40 pinggang 100 panjang 98\n-5XL fit 41-42 pinggang 104 panjang 100\ntoleransi 1-2cm\n\nHappy shopping :)\n\n\nPerhatian :\npengiriman orderan masuk sampai jam 3 sore dikirimkan di hari yg sama selebihnya masuk pengiriman hari besok\n\npengiriman berlaku di hari kerja senin sampai sabtu\ndikarenakan ekpedisi disini nya sebagian ada yg tutup\n\npilih sesuai warna dan ukuran agar tidak terjadi salah kirim barang\n\nbila kami mengirimkan barang tidak sesuai dengan pesanan tanpa konfirmasi kami tukarkan ongkir kami tanggung syarat kirimkan video unboxing\n\nbisa tuker ukuran apabila ukuran kekecilan atau kebesaran tapi kami tidak menanggung ongkirnya\n\n`,
		CategoryID:        729,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "424rekow",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                14,
		Name:              `Otsky Kaos Pocket CB Cotton Combed 24s`,
		Description:       `Keterangan Produk :\n\n- Cotton 24s  170-180 Gsm.\n\n- Warna Tidak Cepat Pudar\n\n- Lembut, Mudah Menyerap Keringat, Tidak Gerah, dan Tidak Kaku.\n\n- Kualitas jahitan terbaik\n\n- Sablon terbaik (Printing / plastisol yang merupakan cat level high end \n\n\n\nKelengkapan Produk  (Packaging Set)\n\n-  Free Sticker\n\n\n\nsize chartd :\n\nPerkiraan Lebar Dan Panjang :\n\nS  (70cm Panjang x 50cm Lebar )\n\nM ( 72cm Panjang x 52cm Lebar )\n\nL  ( 74cm Panjang x 54cm Lebar )\n\nXL ( 76cm Panjang x 56cm Lebar )\n\nXXL ( 78cm Panjang x 58cm Lebar )\n\n* Toleransi jahitan 2-3cm\n\n\n\nKalo mau Cuttingan Oversize\n\n(Pilih 1 size lebih besar, misal pake Size M order size L )\n\n\n\nWarna yang terlihat pada gambar mungkin tidak 100% sama dengan produk yang sebenarnya, disebabkan faktor cahaya pada pengambilan gambar, atau kondisi produk yang digunakan untuk melihat gambar.\n\n \n\nORIGINAL PRODUCT BY OTSKY.\n\n\n\nPENTING INFORMASI PENGIRIMAN SAMEDAY & INSTANT\n\n\n\n- Order di terima pada hari Senin-Jumat ( sebelum jam 12.00 WIB ) akan di kirimkan pada hari yang sama\n\n- Order di terima pada hari Senin-Kamis ( setelah jam 12.00 WIB ) akan di kirimkan pada hari berikutnya\n\n- Order di terima pada hari Jumat ( setelah jam 12.00 WIB ) dan Sabtu-Minggu akan di kirimkan pada hari Senin\n\n- Untuk pesanan instant lewat dari jam 3 sore akan diproses dihari berikutnya\n\n\n\n(*) waktu pengiriman bisa berubah jika ada tanggal merah/libur nasional\n\n\n\nPENGIRIMAN\n\nSENIN s/s SABTU \n\nDILAKUKAN PADA JAM 17.00 WIB \n\nMINGGU TIDAK ADA PENGIRIMAN\n\n\n\nNOTE\n\n- Jika ada kesalahan dari pembeli tidak dapat ditukar / pengembalian dana\n\n- Resi akan di update pada malam hari atau maksimal H+1\n\n- ISI ALAMAT DAN NOMOR TELEFON DENGAN JELAS DAN AKTIF KARENA KESALAHAN  ALAMAT DILUAR TANGGUNG JAWAB KAMI, DAN ALAMAT TIDAK BISA DIGANTI KETIKA PESANAN SUDAH MASUK!\n\nTERIMA KASIH.\n\n\n\nHAPPY SHOOPING OTS 'v'\n\n\n\nCatatan : \n\nUntuk melayani komplain sebelum melakukan unboxing / pembukaan paket harap di video kan. Ditunjukan sebagai bukti bahwa barang mengalami kesalahan mohon maaf.`,
		CategoryID:        711,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "424r21e2",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                15,
		Name:              `Celana Joger PRIA WANITA panjang Jogger Gym training trening trining terening olahraga | CELANA JOGGER PRIA WANITA trening`,
		Description:       `New Produk!!!\n\nProduk joger ini adalah kombinasi untukmu yang sering berakativitas. sangat cocok untuk olahraga,healing atau pun aktivitas lainnya.\n\nBahan Baby terry 100% lembut membuat celana ini nyaman digunakan bahan nya adem, gak panas saat di pakai dan juga gak berbulu..\nkaret pinggang Rib yang memudahkan untuk memakainya serta nyaman di pakai.\nterdapat 2 saku depan \n\n**Detail ukuran:\n👉👉👉pants size chart (unit CM/IN)\n\nM (27/28)    Length:95cm       Waist:102cm    Height: 157-163cm Weight: 45-57kg \nL  (29/30)    Length:96.5cm    Waist:105cm    Height: 159-168cm Weight: 57-67kg \nXL(31/32)    Length:98cm       Waist:108cm    Height: 160-175cm Weight: 67-72kg \nXXL(33/34)  Length:99.5cm   Waist:111cm    Height: 165-185cm Weight: 72-85kg \n\n\n*****WARNA PILIHAN\n-Black\n-Dark Grey\n-Light Grey\n-Navy\n\n# Celanajoger# celanatrainingpanjang # sweetpants #celanajogerpanjangpolosdewasa # CELANAPANJANGJOGER`,
		CategoryID:        731,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "wij3ri1e2",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                16,
		Name:              `PROMO 100RIBU DAPAT 3 YANG LAGI HITS Celana Cargo Pendek Pria Army Loreng Ufc Venum Mma Pantai Gym Lari Fitnes`,
		Description:       `BIG PROMO 100RIBU DAPAT CELANA CARGO LANGSUNG DARI PRODUKSI ( CELANA ) Dengan kualitas internasional harga nasional Bahan tebal, halus dan anti luntur\n\nready celana pendek cargo premium.\n\nMerek sesuai stok terbaru kita Merk : THRASHER (TERBARU)\n\nwarna : \n\n-HItam\n\n-Grey\n\n-Mocca\n\n-Cream\n\nBahan : katun DR.tex tebal halus dan kuat\n\nJenis Bahan : American drill sweding\n\nUkuran : 27 sampai 34\n\nInfo Size Chart Detail Celana :\n\nSize 27 : ( Lingkar Pinggang 76)\n\nSize 28 : ( Lingkar Pinggang 77 )\n\nSize 29: ( Lingkar Pinggang 78 )\n\nSize 30: ( Lingkar Pinggang 79 )\n\nSize 31 : ( Lingkar Pinggang 81 )\n\nSize 32 : ( Lingkar Pinggang 82 )\n\nSize 33 : ( Lingkar Pinggang 83 )\n\nSize 34: ( Lingkar Pinggang 87 )\n\nPanjang Celana 53cm TOLERANSI JAHITAN 1-2cm #celanacargo #celanamurah #celanadistro #celanasantai #celanapendekpria #celanacowok #celanapria #celanacargomurah #celanacargopendek #celanapdl #celana #celanapendek #celanapendekpriamurah#`,
		CategoryID:        732,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "aknd3foiw1e2",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                17,
		Name:              `Topi Bucket Hat Midnight Garden Floral Abu Tua Daun Gray Leaf BucketHat Motif Mancing Pantai TBMI`,
		Description:       `--------- BUDAYAKAN MEMBACA INI DAHULU, SEBELUM MEMBELI ---------\n1000% REAL PICT + FOTO SENDIRI\n\nDeskripsi Produk:\nTOPI BUCKET\n- Bahan KANVAS atau Flannel dikombinasi dengan bahan PURING POLOS di dalamnya\n- Ukuran topi untuk dewasa\n- Lingkar topi kurang lebih 55-58cm (kalo ada meleset sedikit wajar ya kak)\n- Tinggi topi kurang lebih 8,5-10cm\n- Lebar pet topi kurang lebih 5-6cm\n- Garis tengah topi bagian atas kurang lebih 14-15cm\n\nATURAN TOKO KAMI:\n1.  Batas invoice masuk adalah jam 14.00 (Senin - Jumat) dan jam 12.00 (Sabtu), lebih dari itu masuk pengiriman hari berikutnya. TANGGAL MERAH KAMI LIBUR\n2. Jadwal input resi max jam 23.59 (Senin - Sabtu)\n3.  Barang yang anda beli 100% sudah kami sortir, tanpa reject. Apabila terjadi kerusakan pada topi seperti lepasnya kancing topi atau sobek pada bagian sintong topi, itu sah terjadi disebabkan oleh proses pengiriman Ekspedisi (paket terseret-seret, terbanting, tertimpa dll)\n4. Pastikan anda mengisi alamat dengan lengkap (rt/rw, no rumah atau nama jalan), karena jika paket tidak sampai karena ALAMAT TIDAK DITEMUKAN maka bukanlah kesalahan penjual.\n5. Kami tidak menerima pertanyaan "Barang saya sudah dimana?", karena yang mengirim paket anda adalah kurir EKSPEDISI, bukan KAMI. Kami adalah penjual yang bertugas mengirimkan barang ke EKSPEDISI, bukan ke rumah anda.\n6. Jika terjadi retur paket dari EKSPEDISI krn alamat Anda tidak lengkap, maka kami akan menyedekahkan paket tersebut untuk kaum dhuafa atau kotak masjid.\n7. Jika anda tidak mengisi no varian & kami chat anda tidak jawab 1x24 jam maka akan kami kirim RANDOM\n\nDENGAN KLIK MEMBELI, BERARTI KAMI ANGGAP ANDA SUDAH MEMBACA ATURAN TOKO KAMI DAN ANDA MENYETUJUI ATURAN TERSEBUT\nTerima Kasih :)`,
		CategoryID:        793,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "q2edo1e2",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                18,
		Name:              `Otsky Kaos Oversize Salur Biggest Cotton Combed 24s`,
		Description:       `Keterangan Produk :\n\n- Cotton 24s\n\n- Warna Tidak Cepat Pudar\n\n- Lembut, Mudah Menyerap Keringat, Tidak Gerah, dan Tidak Kaku.\n\n- Kualitas jahitan terbaik\n\n- Sablon terbaik (Printing / plastisol yang merupakan cat level high end \n\n\n\nKelengkapan Produk  (Packaging Set)\n\n-  Free Sticker\n\n\n\nKalo mau Cuttingan Oversize\n\n(Pilih 1 size lebih besar, misal pake Size M order size L )\n\n\n\nWarna yang terlihat pada gambar mungkin tidak 100% sama dengan produk yang sebenarnya, disebabkan faktor cahaya pada pengambilan gambar, atau kondisi produk yang digunakan untuk melihat gambar.\n\n \n\nORIGINAL PRODUCT BY OTSKY.\n\n\n\nPENTING INFORMASI PENGIRIMAN SAMEDAY & INSTANT\n\n\n\n- Order di terima pada hari Senin-Jumat ( sebelum jam 12.00 WIB ) akan di kirimkan pada hari yang sama\n\n- Order di terima pada hari Senin-Kamis ( setelah jam 12.00 WIB ) akan di kirimkan pada hari berikutnya\n\n- Order di terima pada hari Jumat ( setelah jam 12.00 WIB ) dan Sabtu-Minggu akan di kirimkan pada hari Senin\n\n- Untuk pesanan instant lewat dari jam 3 sore akan diproses dihari berikutnya\n\n\n\n(*) waktu pengiriman bisa berubah jika ada tanggal merah/libur nasional\n\n\n\nPENGIRIMAN\n\nSENIN s/s SABTU \n\nDILAKUKAN PADA JAM 17.00 WIB \n\nMINGGU TIDAK ADA PENGIRIMAN\n\n\n\nNOTE\n\n- Jika ada kesalahan dari pembeli tidak dapat ditukar / pengembalian dana\n\n- Resi akan di update pada malam hari atau maksimal H+1\n\n- ISI ALAMAT DAN NOMOR TELEFON DENGAN JELAS DAN AKTIF KARENA KESALAHAN  ALAMAT DILUAR TANGGUNG JAWAB KAMI, DAN ALAMAT TIDAK BISA DIGANTI KETIKA PESANAN SUDAH MASUK!\n\nTERIMA KASIH.\n\n\n\nHAPPY SHOOPING OTS 'v'\n\n\n\nCatatan : \n\nUntuk melayani komplain sebelum melakukan unboxing / pembukaan paket harap di video kan. Ditunjukan sebagai bukti bahwa barang mengalami kesalahan mohon maaf.`,
		CategoryID:        711,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "23krjioq",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                19,
		Name:              `Vallina Miya Tunik Patch Pocket Premium Linen Rami - Crinkle Atasan Wanita Muslim Kekinian Fit XL`,
		Description:       `Vallina Outfit saat ini merupakan salah satu lini outfit muslim terbaik dan berkualitas tinggi di antara Local Brand Indonesia. \n\nBahan Linen\nUkuran all size fit to L \nLd  : 110 cm\nPanjang  : 105 cm\nP. Tangan : 57 cm \nToleransi ukuran 1-2cm\nKualitas Premium\n\nBahan Cringkle\nUkuran all size fit to L \nLd  : 110 cm\nPanjang  : 105 cm\nP. Tangan : 57 cm \nToleransi ukuran 1-2cm\n\n**Warna yang terlihat pada gambar mungkin tidak 100% sama dengan produk yang sebenarnya, disebabkan faktor lighting pada proses photoshoot, atau kondisi gadget yang digunakan untuk melihat gambar\n\n**Pastikan alamat yang di tulis ketika checkout diisi dengan sangan LENGKAP guna menghindari kendala pengiriman oleh kurir (Sertakan patokan bila perlu)\n**Pastikan nomor HP yang diisi dalam alamat ketika checkout mudah dihubungi (Tlp. & Sms) / (Sertakan 2 Nomor Hp bila perlu)KEUNGGULAN PRODUK INI : \n✔ Menggunakan bahan dengan hasil pemilihan terbaik sehingga mempunyai kualitas yang bagus\n✔ Penjahit berpengalaman lebih dari 10 tahun sehingga jahitan rapi, kuat dan awet\n✔ Desain yg kekinian sehingga membuat sist/sista percaya diri\n✔ Cocok digunakan di segala macam acara sehingga membuat anda tampil percaya diri dan tampil beda 🥰`,
		CategoryID:        636,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "qjidiwm",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                20,
		Name:              `MOSSDOOM Tas Wanita Tas Selempang MOSS204`,
		Description:       `Selamat datang di official MOSSDOOM store, 100% menjamin keaslian brand produk kami\n\n\n\n-Bahan: kulit PU\n\n- Dimensi: 24 x 7 x 16 cm (P x L x T)\n\n- Warna : Hitam/Aprikot/Hijau/Biru\n\n- Struktur internal: saku penyimpanan besar * 1 saku selip * 1 saku ritsleting * 1, panjang tali bahu sekitar 53,5-110cm\n\n- Berat produk: 0,55 kg\n\n\n\n\n\nfoto:\n\n- Semua foto produk kami adalah foto asli, diambil oleh produk asli.\n\n\n\n\n\nTindakan pencegahan:\n\n- Untuk kapasitas muat laptop, silakan chat kami untuk konfirmasi, ada kesalahan 1-2 cm dalam pengukuran manual produk, harap dipahami.\n\n- Produk dalam stok, Anda dapat memesan secara langsung, jika karena alasan tertentu kami tidak dapat mengirimkannya tepat waktu, kami akan memberi tahu Anda.\n\n- Jika ada pertanyaan tentang produk, beri tahu kami, karena masalah Anda akan dibantu dan diselesaikan.\n\n\n\nInfo:\n\nUntuk Box dan Paperbag dijual secara terpisah \n\n\n\nNote :\n\n1. Wajib menyertakan video unboxing apabila mengajukan pengembalian barang atau retur.Jika tidak ada Mohon maaf,maka tidak dapat diproses.\n\n2. Pengiriman ada setiap harinya dikirim sesuai dengan jadwal dan antrian orderan.\n\n3. Resi akan terupdate secara otomatis, mohon di tunggu.\n\n`,
		CategoryID:        936,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "awkndwqid",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                21,
		Name:              `PREMIUM LEATHER TRAVEL BAG - Tas Koper Kulit Waterproof Sintesis Murah`,
		Description:       `PREMIUM LEATHER TRAVEL BAG\n\nModel: Tas koper travel bag\nGender: Perempuan\nDesign: Glossy waterproof (tahan air)\nRuang: 1 kantong ruang besar, tali pengikat, double resleting, 5 kaki penyangga\nBahan: Premium kulit sintesis\nUkuran: P x L x T = 40 x 15 x 28 cm\n3 Warna: Hitam, cokelat, maroon\n\n100% real pict, stok terbatas. Silakan diorder ya\n\nToko devila: murah, mudah, aman, dan nyaman`,
		CategoryID:        936,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "awdlmwa",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                22,
		Name:              `[ZEAVA] Chelsy Slingbag - Tas Selempang Wanita Slingbag Quilted Sling Bag/Tas Rantai Ulir Selina Sling Valensia - Tas Grosir HON`,
		Description:       `Welcome to ZEAVA Official Shop\n\n✓ Pembelian Sudah Termasuk Tas + Bubel Wrap + Box Kardus\n✓ GARANSI JIKA TAS WAKTU DI TERIMA RUSAK/TDK SESUAI KAMI GANTI 100% \n✓ KWALITAS TERJAGA Premium, banyak yang lebih murah tapi kwalitas saya pastikan beda jauh\n✓ Tips sebelum beli : bisa klik bintang nya terus cek ulasanya, bandingkan bintang 1 nya dan lihat bagaimana respon dari seller nya\n✓ FOTO boleh sama tapi KWALITAS nya kak yang utama, jangan nyesel ya kalo pilih karena faktor harga \n\nBAHAN: Sintetis\nBahan Tebal, Halus & Kuat\nReal Picture - Jika Beda Kami kembalikan 100%\nKarya UMKM Daerah\nHandmade 100% Lokal Kwalitas Premium\n\n✓ UKURAN: 20,5cm x 10cm x 17cm \n\nSling bag berbahan glossy super mewaaah, tebal, jahitan rapih, model stylish!!! Tas ini juga cukup roomy, ga sempit sama sekali girlss!\n\n1kg bisa muat 2 tas\n- Dalam ada furing\n- dalam ada kantong kecil (untuk taruh uang koin)\n- Tali rantai panjang premium\n- jahitan rapi \n- look like import \n\n✓ Klaim Garansi Harus Pakai Foto & Video UNBOXING\n✓ Cara buka paket saat di terima jangan pakai PISAU\n✓ Buka dgn hati-hati\n\nBONUS  :\n✓ FREE BUBBLE WRAP\n✓ PLASTIK BENING PEMBUNGKUS TAS\n\nCATATAN :\n- PENGIRIMAN DI HARI YANG SAMA APABILA PEMBAYARAN SEBELUM JAM 14:00 WIB (TIDAK BERLAKU SAAT PESANAN OVERLOAD DAN MASA PROMO)\n- SEMUA RESI KAMI MENGGUNAKAN SISTEM ONLINE, JADI TIDAK PERLU MINTA RESI DI CHAT\n- BILA BELUM MASUK PENGIRIMAN HARI INI, BISA CEK LAGI BESOKNYA\n- TIDAK MENERIMA SISIPAN WARNA/VARIASI DI CHAT, KAMI AKAN KIRIM SESUAI VARIASI YANG DIPILIH\n- DROPSHIP AMAN APABILA MENGGUNAKAN FITUR DROPSHIPPER\n- BELANJA = SETUJU\n\n\n#JELLYGLOSSY #TASMURAH     \n#TASSLEMPANGWANITA #TAS`,
		CategoryID:        936,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "awdmoaw",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
	{
		ID:                23,
		Name:              `TAS SLING BAG CANVAS 2 SIZE MEDIUM & LARGE`,
		Description:       `CEPET HABIS TAPI CEPAT RESTOCK. jadi sering2 cek stock yaa. Jangan khawatir kak,, krn produksi sendiri,,klo stock habis cepet ready lagi☺️\n\n\nREAD BEFORE ORDER⬇️⬇️⬇️\nInfo yaa,, tas ini ada dua size yaitu\nLarge dan Medium (besar n sedang)  Silakan sesuaikan dengan SELERA dan UKURAN BADAN ya kak.\nKarena.. bs jadi ukuran medium pun cukup besar buat yg badannya standar. \nAtau bisa jadi  ukuran Medium itu kekecilan buat yg suka tas besar meskipun badannya standar.\nNOTED : untuk tas brokenwhite bintik bintik hitam itu bukan jamur atau noda ya kak, itu karena dr bahan alami jadi itu serat seratnya ya kak :)\n\nJadii buat yg suka tas oversize ala2 Korea gituu kayak di foto produk, silakan pilih varian Large. \nDetai ukuran dan spesifikasi ada di bawah yaa!\n\nKlo masih bingung mungkin testimoni dari para Companion bs membantu. cek di penilaian ya :)\n\nSPESIFIKASI:\n\nMATERIAL : CANVAS\nREADY 2 SIZE \nMEDIUM : 27x20x10cm\nLARGE : 35 x25 x10cm\n\nzipper : ❎\nvelcro : ✅\nsnap button : ✅\n\n Ready 3 warna\nHitam\nBroken white\nArmy\n\nNOTE UNTUK PEMBELI :\n- Isi alamat dengan lengkap dan sertakan nomor telepon yang aktif sehingga bisa di hubungi\n- Tidak menerima perubahan pesanan (produk, ukuran yang dipesan) di dalam chat ya.\n- Apabila barang yang diterima tidak sesuai, dan ingin mengajukan complainan WAJIB memberikan video unboxing paket yang diterima. Serta JANGAN terlebih dahulu memberikan penilaian BURUK, jika sudah memberikan penilaian buruk, maka proses pengembalian dan return kita anggap BATAL ya kak,  kami mohon pengertiannya ya :) Terimakasih.\n\n❗REAL PICT❗\nHAPPY SHOPPING COMPANION!!!`,
		CategoryID:        936,
		SellerID:          4,
		HazardousMaterial: false,
		Weight:            decimal.NewFromInt(12),
		Size:              decimal.NewFromInt(27),
		IsNew:             true,
		InternalSKU:       "tfemira",
		ViewCount:         11,
		IsActive:          true,
		CreatedAt:         time.Now(),
		UpdatedAt:         time.Now(),
	},
}
